### ISSUE TITLE
FrontEnd CI 자동화를 한다.

### ISSUE THREAD

**Issue by hozzijeong** [woowacourse-teams/2023-pium#106]
# 어떤 이슈인가요?
origin push를 날리기 전에 `npm run build`와 `npm run build-storybook`을 통해 빌드가 잘 되는지 확인하고, 잘 되지 않는다면 푸시를 막는다.

**Comment by WaiNaat** [comment]
PR merge 전이 아니라 push origin 단계에서 검사하는건가요??

**Comment by hozzijeong** [comment]
```
on:
  push:
    paths: 'frontend/**'
  pull_request:
    branches:
      - develop
      - main
    paths: 'frontend/**'
```
다음과 같이 frontend에서 Push되는 것과 develop과 main에서 pr이 작성된는 시기에 작업할 수 있도록 설정했습니다.
